### ISSUE TITLE
problème de test webservice

### ISSUE THREAD

**Issue by l3miage-liuxi** [l3-miage-cl-ihm/projet-integrateur-2024-partie-ro-webservice-l3miage-liuxi#1]
Nos tests unitaires donnent les résultats souhaités sans problème, mais lorsque nous essayons d'utiliser java -jar server/target/integrator-project-planner.jar pour le test webservice, nous n'obtenons que des tableaux vides. Je n'arrive pas à trouver la cause de ce problème.

Par ailleurs, comment faire le test webservice si l'on utilise Intellij comme éditeur ?

(Une partie du test unitaire est commentée car la méthode PartitionKCentre est actuellement utilisée dans le planner pour l'instanciation. Pour la partie PartitionAlea, vous pouvez changer la méthode d'instanciation dans la class planner et modifier la partie du test en conséquence.)

J'espère que vous prendrez le temps de nous aider. Merci d'avance !  ：）

**Comment by AlexDmr** [comment]
Je vous propose d'assigner ce problème à Nicolas Marihno.
Par ailleurs, décrivez mieux le cmportement que vous avez, quels sont précisément les commandes que vous exécutés, quel est votre configuration de test ?
Comment reproduire le bon comportement ?
Comment reproduire le comportement probélamatique ?

**Comment by l3miage-liuxi** [comment]
> Je vous propose d'assigner ce problème à Nicolas Marihno. Par ailleurs, décrivez mieux le cmportement que vous avez, quels sont précisément les commandes que vous exécutés, quel est votre configuration de test ? Comment reproduire le bon comportement ? Comment reproduire le comportement probélamatique ?

Ok, merci pour votre suggestion, je vais ajouter des informations complètes sur la base de votre suggestion. ；）

**Comment by l3miage-liuxi** [comment]
Le problème est résolu.
